<!DOCTYPE html>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Main Page - Daft Punk</title>
		<meta name="description" content="Daft Punk fansite for CMP204 coursework">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>
		
		<!--Styles-->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
			  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
			  crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="styles/slick.css"/>
		<link rel="stylesheet" type="text/css" href="styles/slick-theme.css"/>
		<link rel="stylesheet" href="styles/mainStyle.css">
		
		<!--Scripts-->
		<script src="https://code.jquery.com/jquery-3.5.1.js"
				integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
		<script type="text/javascript" src="scripts/js/slick.js"></script>
		<script type="text/javascript" src="scripts/js/slickInit.js"></script>
		<script type="text/javascript" src="scripts/js/themeChange.js"></script>
	
	</head>
	<body>

		<?php session_start(); include ('master/header.php') ?>
		
		<div class="container">
			<h1>Privacy Policy</h1>
			<p>Last updated: December 15, 2020</p>
			<p>This Privacy Policy describes my policies and procedures on the collection, use and disclosure of your information when you use the Service and tells you about your privacy rights and how the law protects you.</p>
			<p>I use your Personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/" target="_blank">Privacy Policy Generator</a>.</p>
			<h1>Interpretation and Definitions</h1>
			<h2>Interpretation</h2>
			<p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
			<h2>Definitions</h2>
			<p>For the purposes of this Privacy Policy:</p>
			<ul>
				<li>
					<p><strong>Account</strong> means a unique account created for you to access the website or parts of the website.</p>
				</li>
				<li>
					<p><strong>Developer</strong> (referred to as either &quot;the Developer&quot;, &quot;I&quot;, &quot;me&quot; or &quot;my&quot; in this Agreement) refers to Daft Punk Fansite.</p>
				</li>
				<li>
					<p><strong>Cookies</strong> are small files that are placed on your computer, mobile device or any other device by a website, containing the details of your browsing history on that website among its many uses.</p>
				</li>
				<li>
					<p><strong>Country</strong> refers to:  United Kingdom</p>
				</li>
				<li>
					<p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
				</li>
				<li>
					<p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
				</li>
				<li>
					<p><strong>Service</strong> refers to the Website.</p>
				</li>
				<li>
					<p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Developer. It refers to third-party companies or individuals employed by the Developer to facilitate the Service, to provide the Service on behalf of the Developer, to perform services related to the Service or to assist the Developer in analyzing how the Service is used.</p>
				</li>
				<li>
					<p><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</p>
				</li>
				<li>
					<p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
				</li>
				<li>
					<p><strong>Website</strong> refers to Daft Punk Fansite, accessible from <a href="https://mayar.abertay.ac.uk/%7E1901124/cmp204/coursework2/" rel="external nofollow noopener" target="_blank">https://mayar.abertay.ac.uk/~1901124/cmp204/coursework2/</a></p>
				</li>
				<li>
					<p><strong>you</strong> means the individual accessing or using the Service, or the Developer, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
				</li>
			</ul>
			<h1>Collecting and Using your Personal Data</h1>
			<h2>Types of Data Collected</h2>
			<h3>Personal Data</h3>
			<p>While using the website, I may ask you to provide me with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:</p>
			<ul>
				<li>
					<p>Email address</p>
				</li>
				<li>
					<p>First name and last name</p>
				</li>
				<li>
					<p>Usage Data</p>
				</li>
			</ul>
			<h3>Usage Data</h3>
			<p>Usage Data is collected automatically when using the Service.</p>
			<p>Usage Data may include information such as your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of the website that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
			<p>When you access the Service by or through a mobile device, I may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.</p>
			<p>I may also collect information that your browser sends whenever you visit the website or when you access the Service by or through a mobile device.</p>
			<h3>Tracking Technologies and Cookies</h3>
			<p>I use Cookies and similar tracking technologies to track the activity on the website and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze the website. The technologies I use may include:</p>
			<ul>
				<li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on your Device. you can instruct your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if you do not accept Cookies, you may not be able to use some parts of the website. Unless you have adjusted your browser setting so that it will refuse Cookies, the website may use Cookies.</li>
				<li><strong>Flash Cookies.</strong> Certain features of the website may use local stored objects (or Flash Cookies) to collect and store information about your preferences or your activity on the website. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies. For more information on how you can delete Flash Cookies, please read &quot;Where can I change the settings for disabling, or deleting local shared objects?&quot; available at <a href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_" rel="external nofollow noopener" target="_blank">https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_</a></li>
				<li><strong>Web Beacons.</strong> Certain sections of the website and my emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Developer, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
			</ul>
			<p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on your personal computer or mobile device when you go offline, while Session Cookies are deleted as soon as you close your web browser. Learn more about cookies: <a href="https://www.freeprivacypolicy.com/blog/cookies/" target="_blank">Cookies: What Do They Do?</a>.</p>
			<p>I use both Session and Persistent Cookies for the purposes set out below:</p>
			<ul>
				<li>
					<p><strong>Necessary / Essential Cookies</strong></p>
					<p>Type: Session Cookies</p>
					<p>Administered by: me</p>
					<p>Purpose: These Cookies are essential to provide you with services available through the Website and to enable you to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that you have asked for cannot be provided, and I only use these Cookies to provide you with those services.</p>
				</li>
				<li>
					<p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
					<p>Type: Persistent Cookies</p>
					<p>Administered by: me</p>
					<p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
				</li>
				<li>
					<p><strong>Functionality Cookies</strong></p>
					<p>Type: Persistent Cookies</p>
					<p>Administered by: me</p>
					<p>Purpose: These Cookies allow me to remember choices you make when you use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide you with a more personal experience and to avoid you having to re-enter your preferences every time you use the Website.</p>
				</li>
			</ul>
			<p>For more information about the cookies I use and your choices regarding cookies, please visit my Cookies Policy or the Cookies section of my Privacy Policy.</p>
			<h2>Use of your Personal Data</h2>
			<p>The Developer may use Personal Data for the following purposes:</p>
			<ul>
				<li>
					<p><strong>To provide and maintain the website</strong>, including to monitor the usage of the website.</p>
				</li>
				<li>
					<p><strong>To manage your Account:</strong> to manage your registration as a user of the Service. The Personal Data you provide can give you access to different functionalities of the Service that are available to you as a registered user.</p>
				</li>
				<li>
					<p><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services you have purchased or of any other contract with me through the Service.</p>
				</li>
				<li>
					<p><strong>To contact you:</strong> To contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
				</li>
				<li>
					<p><strong>To provide you</strong> with news, special offers and general information about other goods, services and events which I offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information.</p>
				</li>
				<li>
					<p><strong>To manage your requests:</strong> To attend and manage your requests to me.</p>
				</li>
				<li>
					<p><strong>For business transfers:</strong> I may use your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of my assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by me about the website users is among the assets transferred.</p>
				</li>
				<li>
					<p><strong>For other purposes</strong>: I may use your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of my promotional campaigns and to evaluate and improve the website, products, services, marketing and your experience.</p>
				</li>
			</ul>
			<p>I may share your personal information in the following situations:</p>
			<ul>
				<li><strong>With Service Providers:</strong> I may share your personal information with Service Providers to monitor and analyze the use of the website,  to contact you.</li>
				<li><strong>For business transfers:</strong> I may share or transfer your personal information in connection with, or during negotiations of, any merger, sale of Developer assets, financing, or acquisition of all or a portion of my business to another Developer.</li>
				<li><strong>With Affiliates:</strong> I may share your information with my affiliates, in which case I will require those affiliates to honor this Privacy Policy. Affiliates include my parent Developer and any other subsidiaries, joint venture partners or other companies that I control or that are under common control with me.</li>
				<li><strong>With business partners:</strong> I may share your information with my business partners to offer you certain products, services or promotions.</li>
				<li><strong>With other users:</strong> when you share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If you interact with other users or register through a Third-Party Social Media Service, your contacts on the Third-Party Social Media Service may see your name, profile, pictures and description of your activity. Similarly, other users will be able to view descriptions of your activity, communicate with you and view your profile.</li>
				<li><strong>With your consent</strong>: I may disclose your personal information for any other purpose with your consent.</li>
			</ul>
			<h2>Retention of your Personal Data</h2>
			<p>The Developer will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. I will retain and use your Personal Data to the extent necessary to comply with my legal obligations (for example, if I are required to retain your data to comply with applicable laws), resolve disputes, and enforce my legal agreements and policies.</p>
			<p>The Developer will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of the website, or I are legally obligated to retain this data for longer time periods.</p>
			<h2>Transfer of your Personal Data</h2>
			<p>your information, including Personal Data, is processed at the Developer's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
			<p>your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
			<p>The Developer will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
			<h2>Disclosure of your Personal Data</h2>
			<h3>Business Transactions</h3>
			<p>If the Developer is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. I will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
			<h3>Law enforcement</h3>
			<p>Under certain circumstances, the Developer may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
			<h3>Other legal requirements</h3>
			<p>The Developer may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
			<ul>
				<li>Comply with a legal obligation</li>
				<li>Protect and defend the rights or property of the Developer</li>
				<li>Prevent or investigate possible wrongdoing in connection with the Service</li>
				<li>Protect the personal safety of Users of the Service or the public</li>
				<li>Protect against legal liability</li>
			</ul>
			<h2>Security of your Personal Data</h2>
			<p>The security of your Personal Data is important to me, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While I strive to use commercially acceptable means to protect your Personal Data, I cannot guarantee its absolute security.</p>
			<h1>Links to Other Websites</h1>
			<p>the website may contain links to other websites that are not operated by me. If you click on a third party link, you will be directed to that third party's site. I strongly advise you to review the Privacy Policy of every site you visit.</p>
			<p>I have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
			<h1>Changes to this Privacy Policy</h1>
			<p>I may update my Privacy Policy from time to time. I will notify you of any changes by posting the new Privacy Policy on this page.</p>
			<p>I will let you know via email and/or a prominent notice on the website, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
			<p>you are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
			<h1>Contact me</h1>
			<p>If you have any questions about this Privacy Policy, you can contact me:</p>
			<ul>
				<li class="mainBody">By email: 1901124@uad.ac.uk</li>
			</ul>
		</div>
		
		<?php include('master/footer.php')?>
		
		
	</body>
</html>
